name: "CodeQL_Anlysis"

on:
  workflow_call:
    inputs:
      RUNNER_TYPE:
        description: 'value for the runs-on arg'
        required: true
        type: string
      LANGUAGES:
        description: 'Languages to scan'
        required: true
        type: string

jobs:
  scan:
    runs-on: ["${{ inputs.RUNNER_TYPE }}"]
    permissions:
      actions: read
      contents: read
      security-events: write

#    strategy:
#      fail-fast: true
#      matrix:
#        language: ${{ fromJSON(inputs.LANGUAGES) }}
        
    steps:
    - name: check_inputs
      run: |
        echo "RUNNER_TYPE = ${{ inputs.RUNNER_TYPE }}"
        echo "LANGUAGES = ${{ inputs.LANGUAGES }}"
        env | grep GITHUB

#    - name: Initialize CodeQL
#      uses: github/codeql-action/init@v2
#      with:
#        languages: ${{ matrix.language }}
#
#    - name: Autobuild
#      uses: github/codeql-action/autobuild@v2
#
#    - name: Perform CodeQL Analysis
#      uses: github/codeql-action/analyze@v2
#      with:
#        category: "/language:${{matrix.language}}"
